//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PolyWars.Server.WebService.ConsoleClient.ServiceReferenceWCF {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReferenceWCF.IFlipCaseService")]
    public interface IFlipCaseService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFlipCaseService/FlipTheCase", ReplyAction="http://tempuri.org/IFlipCaseService/FlipTheCaseResponse")]
        PolyWars.Server.WebService.StringData FlipTheCase(PolyWars.Server.WebService.StringData sd);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFlipCaseService/FlipTheCase", ReplyAction="http://tempuri.org/IFlipCaseService/FlipTheCaseResponse")]
        System.Threading.Tasks.Task<PolyWars.Server.WebService.StringData> FlipTheCaseAsync(PolyWars.Server.WebService.StringData sd);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IFlipCaseServiceChannel : PolyWars.Server.WebService.ConsoleClient.ServiceReferenceWCF.IFlipCaseService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class FlipCaseServiceClient : System.ServiceModel.ClientBase<PolyWars.Server.WebService.ConsoleClient.ServiceReferenceWCF.IFlipCaseService>, PolyWars.Server.WebService.ConsoleClient.ServiceReferenceWCF.IFlipCaseService {
        
        public FlipCaseServiceClient() {
        }
        
        public FlipCaseServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public FlipCaseServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FlipCaseServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FlipCaseServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public PolyWars.Server.WebService.StringData FlipTheCase(PolyWars.Server.WebService.StringData sd) {
            return base.Channel.FlipTheCase(sd);
        }
        
        public System.Threading.Tasks.Task<PolyWars.Server.WebService.StringData> FlipTheCaseAsync(PolyWars.Server.WebService.StringData sd) {
            return base.Channel.FlipTheCaseAsync(sd);
        }
    }
}
